version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle@5.1.23 openzeppelin-solidity@2.1.3 multi-token-standard@0.8.4
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle openzeppelin-solidity@2.1.3 multi-token-standard@0.8.4
      - npx truffle test
stages:
  - pipeline:
      jobs:
        - compile
        # - test