version: 1
jobs:
  compile:
    image: node:12
    script:
        - npm install
        - npx truffle compile

  deploy_to_rinkeby_manually:
    image: node:12
    type:
        name: ethereum/deploy
    script:
        - npm install
        - npx truffle migrate --network rinkeby_metamask --reset
        - npx superblocks-cli collect-artifacts
stages:
  - pipeline:
      jobs:
        # - compile
        - deploy_to_rinkeby_manually